---
name: postfix

releases:
- name: postfix
  version: latest

update:
  canaries: 1
  canary_watch_time: 3000-180000
  update_watch_time: 3000-180000
  max_in_flight: 2

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: postfix
  stemcell: default
  vm_type: default
  instances: 1
  azs: [z1, z2]
  networks:
  - name: manual
    static_ips: [10.244.8.64]
  jobs:
  - release: postfix
    name: postfix
    properties:
      postfix:
        relayhost: ((postfix_relayhost))
        root_recipient: ((postfix_root_recipient))
        mynetworks: ((postfix_mynetworks))
        myhostname: ((postfix_myhostname))
        use_tls: ((postfix_use_tls))
        tls_cert: ((postfix_ssl.certificate))
        tls_key: ((postfix_ssl.private_key))
        use_sasl: ((postfix_use_sasl))
        dkim_privatekey: ((postfix_dkim_privatekey))
        dkim_maildomain: ((postfix_dkim_maildomain))

variables:
- name: postfix_ca
  type: certificate
  options:
    is_ca: true
    common_name: postfix_ca
- name: postfix_ssl
  type: certificate
  options:
    ca: postfix_ca
    common_name: 10.244.8.64
    alternative_names: [ 10.244.8.64 ]
- name: cloudgov_pw
  type: password
